version: '2'
services:
  webapp:
    image: coper/coper-webapp:v1.0.0
    build:
      context: .
      dockerfile: Dockerfile
    network_mode: host
    ports:
      - "8080:8080"
    depends_on:
      - mongo

  mongo:
    image: mvertes/alpine-mongo
    network_mode: host
    expose:
      - 27017
    ports:
      - "27017:27017"
